version: "3"
services:
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data

  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    # env_file:
    #   - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
